apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrate
  namespace: syla
spec:
  backoffLimit: 3 
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: docker.io/qwert7750/syla:v3
          command: ["python", "manage.py", "migrate", "--noinput"]
          envFrom:
            - configMapRef:
                name: syla-config
            - secretRef:
                name: syla-secrets