stages:
  - lint
  - test
  - build

lint:
  stage: lint
  image: python:3.12-slim
  before_script:
    - pip install --no-cache-dir -r requirements/dev.txt
  script:
    - black --check .
    - flake8 .

test:
  stage: test
  image: python:3.12-slim
  services:
    - postgres:16-alpine
  variables:
    POSTGRES_DB: test_db
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    DJANGO_SECRET_KEY: ci-test-key
    DJANGO_SETTINGS_MODULE: config.settings.production
    SECURE_SSL_REDIRECT: "False"
    DB_NAME: test_db
    DB_USER: postgres
    DB_PASSWORD: postgres
    DB_HOST: postgres
    DB_PORT: 5432
  before_script:
    - pip install --no-cache-dir -r requirements/production.txt
    - python manage.py collectstatic --noinput
  script:
    - python manage.py test

  build:
  stage: build
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_TLS_VERIFY: 1
    DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"
    IMAGE_TAG: "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/syla-yednosti:$CI_COMMIT_SHORT_SHA"
  before_script:
    - apk add --no-cache aws-cli
    - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  script:
    - docker build -f Dockerfile.prod -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'